# Generated by Django 5.0 on 2025-09-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_reviewupvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='upvotes',
        ),
        migrations.DeleteModel(
            name='ReviewUpvote',
        ),
    ]
